Parameters:
  EcrName:
    Type: String
    Default: mlmax-repo

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrName
      # RepositoryPolicyText:
      #   Version: "2012-10-17"
      #   Statement:
      #     - Sid: AllowPushPull
      #       Effect: Allow
      #       Principal:
      #         AWS:
      #           - "arn:aws:iam::123456789012:user/Bob"
      #           - "arn:aws:iam::123456789012:user/Alice"
      #       Action:
      #         - "ecr:GetDownloadUrlForLayer"
      #         - "ecr:BatchGetImage"
      #         - "ecr:BatchCheckLayerAvailability"
      #         - "ecr:PutImage"
      #         - "ecr:InitiateLayerUpload"
      #         - "ecr:UploadLayerPart"
      #         - "ecr:CompleteLayerUpload"

Outputs:
  EcrRepo:
    # Repo name
    Value: !Ref MyRepository
