AWSTemplateFormatVersion: 2010-09-09
Description: "Create s3 buckets"
Parameters:
  S3BucketName:
    Type: String
    Default: mlmax-bucket
  TagName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      Tags:
        - Key: Name
          Value: !Ref TagName

Outputs:
  S3BucketInfo:
    Value: !Ref S3Bucket
