AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Internet:
    Type: String
    Default: Enabled
    AllowedValues:
      - Enabled
      - Disabled

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ec2.yaml
