AWSTemplateFormatVersion: "2010-09-09"

Description: Create a role that authorizes access to admin users in another account

Parameters:
  RoleName:
    Type: String
    Default: CrossAccountRoleTest

  SourceAccountId:
    Description: 12 digit id of the account containing the users to which you're granting access
    Type: String
    MaxLength: 12
    MinLength: 12

Resources:
  AssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Policies:
        - PolicyName: AdminUser
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref SourceAccountId
                  - :root
            Action:
              - sts:AssumeRole

Outputs:
  AssumeRole:
    Value: !GetAtt AssumeRole.Arn
