AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Step Functions - State Machine

# Added by script
Parameters:
  PipelineName:
    Type: String
  SagerMakerRoleArn:
    Type: String
  WorkflowExecutionRoleArn:
    Type: String
  TargetEnv:
    Type: String

Resources:
  StateMachineComponent:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      # Replaced by script
      StateMachineName: !Sub "${PipelineName}-Inference-${TargetEnv}"
      # Replaced by script
      DefinitionString: !Sub |-
        {
          "StartAt": "SageMaker Preprocess Model Creating step",
          "States": {
            "SageMaker Preprocess Model Creating step": {
              "Parameters": {
                "ModelName.$": "$$.Execution.Input['ProcModelName']",
                "PrimaryContainer": {
                  "Image": "683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3",
                  "Environment": {
                    "SAGEMAKER_PROGRAM": "preprocessing.py",
                    "SAGEMAKER_SUBMIT_DIRECTORY.$": "$$.Execution.Input['SmProcSubmitDirUrl']",
                    "SAGEMAKER_ENABLE_CLOUDWATCH_METRICS": "false",
                    "SAGEMAKER_CONTAINER_LOG_LEVEL": "20",
                    "SAGEMAKER_REGION": "us-east-1"
                  },
                  "ModelDataUrl.$": "$$.Execution.Input['ProcModelS3']"
                },
                "ExecutionRoleArn": "${SagerMakerRoleArn}"
              },
              "Resource": "arn:aws:states:::sagemaker:createModel",
              "Type": "Task",
              "Next": "SageMaker Preprocess BatchTransform step",
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "SageMaker Preprocess BatchTransform step": {
              "Resource": "arn:aws:states:::sagemaker:createTransformJob.sync",
              "Parameters": {
                "TransformJobName.$": "$$.Execution.Input['PreprocessingJobName']",
                "ModelName.$": "$$.Execution.Input['ProcModelName']",
                "TransformInput": {
                  "DataSource": {
                    "S3DataSource": {
                      "S3DataType": "S3Prefix",
                      "S3Uri.$": "$$.Execution.Input['InputDataURL']"
                    }
                  },
                  "SplitType": "Line"
                },
                "TransformOutput": {
                  "S3OutputPath.$": "$$.Execution.Input['PreprocessedTestDataURL']"
                },
                "TransformResources": {
                  "InstanceCount": 1,
                  "InstanceType": "ml.c5.xlarge"
                },
                "BatchStrategy": "MultiRecord",
                "MaxPayloadInMB": 100
              },
              "Type": "Task",
              "Next": "SageMaker Inference Model Creating step",
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "SageMaker Inference Model Creating step": {
              "Parameters": {
                "ModelName.$": "$$.Execution.Input['ModelName']",
                "PrimaryContainer": {
                  "Image": "683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3",
                  "Environment": {
                    "SAGEMAKER_PROGRAM": "inference.py",
                    "SAGEMAKER_SUBMIT_DIRECTORY.$": "$$.Execution.Input['SmSubmitDirUrl']",
                    "SAGEMAKER_ENABLE_CLOUDWATCH_METRICS": "false",
                    "SAGEMAKER_CONTAINER_LOG_LEVEL": "20",
                    "SAGEMAKER_REGION": "us-east-1"
                  },
                  "ModelDataUrl.$": "$$.Execution.Input['ModelS3']"
                },
                "ExecutionRoleArn": "${SagerMakerRoleArn}"
              },
              "Resource": "arn:aws:states:::sagemaker:createModel",
              "Type": "Task",
              "Next": "SageMaker Inference BatchTransform step",
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "SageMaker Inference BatchTransform step": {
              "Resource": "arn:aws:states:::sagemaker:createTransformJob.sync",
              "Parameters": {
                "TransformJobName.$": "$$.Execution.Input['BatchTransformJobName']",
                "ModelName.$": "$$.Execution.Input['ModelName']",
                "TransformInput": {
                  "DataSource": {
                    "S3DataSource": {
                      "S3DataType": "S3Prefix",
                      "S3Uri.$": "$$.Execution.Input['PreprocessedTestDataURL']"
                    }
                  },
                  "SplitType": "Line"
                },
                "TransformOutput": {
                  "S3OutputPath.$": "$$.Execution.Input['OutputPathURL']"
                },
                "TransformResources": {
                  "InstanceCount": 1,
                  "InstanceType": "ml.c5.xlarge"
                },
                "BatchStrategy": "MultiRecord"
              },
              "Type": "Task",
              "End": true,
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "ML Workflow failed": {
              "Cause": "SageMakerProcessingJobFailed",
              "Type": "Fail"
            }
          }
        }
      # Replaced by script
      RoleArn: !Sub "${WorkflowExecutionRoleArn}"
