name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '02 02 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale. If left untouched, it will be automatically closed in 7 days.'
        stale-pr-message: 'This pull request is stale. If left untouched, it will be automatically closed in 7 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
